-- Drop all tables in reverse dependency order
DROP TABLE IF EXISTS Feedback CASCADE;
DROP TABLE IF EXISTS Award CASCADE;
DROP TABLE IF EXISTS Contract CASCADE;
DROP TABLE IF EXISTS Production CASCADE;
DROP TABLE IF EXISTS Content_Creator CASCADE;
DROP TABLE IF EXISTS Agent CASCADE;
